//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRTSekreterya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adre()
        {
            this.sirkets = new HashSet<sirket>();
        }
    
        public int adresID { get; set; }
        public int adresUlkeID { get; set; }
        public Nullable<int> adresILID { get; set; }
        public string adresIlce { get; set; }
        public string adresPostaKodu { get; set; }
        public string adresAdres { get; set; }
        public string adresTip { get; set; }
        public Nullable<int> adresKisiID { get; set; }
    
        public virtual kisi kisi { get; set; }
        public virtual sehir sehir { get; set; }
        public virtual ulke ulke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sirket> sirkets { get; set; }
    }
}
