//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRTSekreterya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletisimToKisi
    {
        public int itkID { get; set; }
        public Nullable<int> iletisimID { get; set; }
        public Nullable<int> kisiID { get; set; }
        public string value { get; set; }
    
        public virtual iletisim iletisim { get; set; }
        public virtual kisi kisi { get; set; }
    }
}
