//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using TRTSekreterya.Models;

public partial class RandevuEntities : DbContext
{
    public RandevuEntities()
        : base("name=RandevuEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<adre> adres { get; set; }
    public virtual DbSet<birim> birims { get; set; }
    public virtual DbSet<iletisim> iletisims { get; set; }
    public virtual DbSet<iletisimToKisi> iletisimToKisis { get; set; }
    public virtual DbSet<iletisimToSirket> iletisimToSirkets { get; set; }
    public virtual DbSet<kisi> kisis { get; set; }
    public virtual DbSet<plan> plans { get; set; }
    public virtual DbSet<planToKisi> planToKisis { get; set; }
    public virtual DbSet<sehir> sehirs { get; set; }
    public virtual DbSet<sirket> sirkets { get; set; }
    public virtual DbSet<ulke> ulkes { get; set; }
    public virtual DbSet<user> users { get; set; }
    public virtual DbSet<yetkiLogin> yetkiLogins { get; set; }
}
