//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRTSekreterya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class planToKisi
    {
        public int pkID { get; set; }
        public Nullable<int> pkKisiID { get; set; }
        public Nullable<int> pkPlanID { get; set; }
        public Nullable<bool> pkisSource { get; set; }
    
        public virtual kisi kisi { get; set; }
        public virtual plan plan { get; set; }
    }
}
