//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRTSekreterya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plan()
        {
            this.planToKisis = new HashSet<planToKisi>();
        }
    
        public int planID { get; set; }
        public string planUzunBilgi { get; set; }
        public string planKisaBilgi { get; set; }
        public Nullable<System.DateTime> planStartTarih { get; set; }
        public Nullable<System.DateTime> planEndTarih { get; set; }
        public string planMekan { get; set; }
        public Nullable<bool> planisCompleted { get; set; }
        public Nullable<bool> planFullDay { get; set; }
        public string planEkBilgi { get; set; }
        public string planColor { get; set; }
        public Nullable<int> planUserID { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<planToKisi> planToKisis { get; set; }
    }
}
