//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRTSekreterya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.plans = new HashSet<plan>();
        }
    
        public int userID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> userYetkiID { get; set; }
        public string userAdSoyad { get; set; }
        public Nullable<int> userBirimID { get; set; }
    
        public virtual birim birim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plan> plans { get; set; }
        public virtual yetkiLogin yetkiLogin { get; set; }
    }
}
